hackaliste_evenement:
    resource: "@hackalisteBundle/Resources/config/routing/evenement.yml"
    prefix:   /evenement

hackaliste_homepage:
    path:     /
    defaults: { _controller: hackalisteBundle:Default:index }
